import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import organizationRouter from "./organization";
import usersRouter from "./users";
import rolesRouter from "./roles";
import operationsRouter from "./operations";
import groupsRouter from "./groups";
import showBookRouter from "./show-book";
import agendaRouter from "./agenda";
import scalesRouter from "./scales";
import dailyBookRouter from "./daily-book";
import operationalPanelRouter from "./operational-panel";
import myDayRouter from "./my-day";
import noticesRouter from "./notices";
import historyRouter from "./history";
import messagesRouter from "./messages";
import deliveriesRouter from "./deliveries";
import libraryRouter from "./library";
import checkInsRouter from "./check-ins";
import requestsRouter from "./requests";
import delegationsRouter from "./delegations";
import tasksRouter from "./tasks";
import insightsRouter from "./insights";
import restrictionsRouter from "./restrictions";
import supervisorRequestsRouter from "./supervisor-requests";
import notificationsRouter from "./notifications";
import responsibilitiesRouter from "./responsibilities";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use(organizationRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(operationsRouter);
router.use(groupsRouter);
router.use(showBookRouter);
router.use(agendaRouter);
router.use(scalesRouter);
router.use(dailyBookRouter);
router.use(operationalPanelRouter);
router.use(myDayRouter);
router.use(noticesRouter);
router.use(historyRouter);
router.use(messagesRouter);
router.use(deliveriesRouter);
router.use(libraryRouter);
router.use(checkInsRouter);
router.use(requestsRouter);
router.use(delegationsRouter);
router.use(tasksRouter);
router.use(insightsRouter);
router.use(restrictionsRouter);
router.use(supervisorRequestsRouter);
router.use(notificationsRouter);
router.use(responsibilitiesRouter);

export default router;
