import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import organizationRouter from "./organization.js";
import usersRouter from "./users.js";
import rolesRouter from "./roles.js";
import operationsRouter from "./operations.js";
import groupsRouter from "./groups.js";
import showBookRouter from "./show-book.js";
import agendaRouter from "./agenda.js";
import scalesRouter from "./scales.js";
import dailyBookRouter from "./daily-book.js";
import operationalPanelRouter from "./operational-panel.js";
import myDayRouter from "./my-day.js";
import noticesRouter from "./notices.js";
import historyRouter from "./history.js";
import messagesRouter from "./messages.js";
import deliveriesRouter from "./deliveries.js";
import libraryRouter from "./library.js";
import checkInsRouter from "./check-ins.js";
import requestsRouter from "./requests.js";
import delegationsRouter from "./delegations.js";
import tasksRouter from "./tasks.js";
import insightsRouter from "./insights.js";
import restrictionsRouter from "./restrictions.js";
import supervisorRequestsRouter from "./supervisor-requests.js";
import notificationsRouter from "./notifications.js";
import responsibilitiesRouter from "./responsibilities.js";
import anthropicRouter from "./anthropic/index.js";
import asaRouter from "./asa.js";
import folgasRouter from "./folgas.js";
import activitiesRouter from "./activities.js";
import { blockIfMustChangePassword } from "../middlewares/mustChangePassword.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use(blockIfMustChangePassword);
router.use(organizationRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(operationsRouter);
router.use(groupsRouter);
router.use(showBookRouter);
router.use(agendaRouter);
router.use(scalesRouter);
router.use(dailyBookRouter);
router.use(operationalPanelRouter);
router.use(myDayRouter);
router.use(noticesRouter);
router.use(historyRouter);
router.use(messagesRouter);
router.use(deliveriesRouter);
router.use(libraryRouter);
router.use(checkInsRouter);
router.use(requestsRouter);
router.use(delegationsRouter);
router.use(tasksRouter);
router.use(insightsRouter);
router.use(restrictionsRouter);
router.use(supervisorRequestsRouter);
router.use(notificationsRouter);
router.use(responsibilitiesRouter);
router.use(anthropicRouter);
router.use(asaRouter);
router.use(folgasRouter);
router.use(activitiesRouter);

export default router;
