import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import organizationRouter from "./organization.js";
import usersRouter from "./users.js";
import rolesRouter from "./roles.js";
import operationsRouter from "./operations.js";
import groupsRouter from "./groups.js";
import showBookRouter from "./show-book.js";
import agendaRouter from "./agenda.js";
import scalesRouter from "./scales.js";
import escalasRouter from "./escalas.js";
import dailyBookRouter from "./daily-book.js";
import operationalPanelRouter from "./operational-panel.js";
import myDayRouter from "./my-day.js";
import noticesRouter from "./notices.js";
import communicationHubRouter from "./communication-hub.js";
import historyRouter from "./history.js";
import perfilRouter from "./perfil.js";
import solicitacoesRouter from "./solicitacoes.js";
import internalRouter from "./internal.js";
import messagesRouter from "./messages.js";
import deliveriesRouter from "./deliveries.js";
import libraryRouter from "./library.js";
import checkInsRouter from "./check-ins.js";
import shiftCheckInsRouter from "./shift-checkins.js";
import requestsRouter from "./requests.js";
import delegationsRouter from "./delegations.js";
import tasksRouter from "./tasks.js";
import insightsRouter from "./insights.js";
import restrictionsRouter from "./restrictions.js";
import supervisorRequestsRouter from "./supervisor-requests.js";
import notificationsRouter from "./notifications.js";
import responsibilitiesRouter from "./responsibilities.js";
import asaRouter from "./asa.js";
import folgasRouter from "./folgas.js";
import operationalCycleRouter from "./operational-cycle.js";
import activitiesRouter from "./activities.js";
import scheduleConflictsRouter from "./schedule-conflicts.js";
import formationsRouter from "./formations.js";
import occurrencesRouter from "./occurrences.js";
import entitiesRouter from "./entities.js";
import areasLocationsRouter from "./areas-locations.js";
import block7Router from "./block7.js";
import { blockIfMustChangePassword } from "../middlewares/mustChangePassword.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use(blockIfMustChangePassword);
router.use(organizationRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(operationsRouter);
router.use(groupsRouter);
router.use(block7Router);
router.use(showBookRouter);
router.use(agendaRouter);
router.use(scalesRouter);
router.use(escalasRouter);
router.use(dailyBookRouter);
router.use(operationalPanelRouter);
router.use(myDayRouter);
router.use(noticesRouter);
router.use(communicationHubRouter);
router.use(historyRouter);
router.use(perfilRouter);
router.use(solicitacoesRouter);
router.use(internalRouter);
router.use(messagesRouter);
router.use(deliveriesRouter);
router.use(libraryRouter);
router.use(checkInsRouter);
router.use(shiftCheckInsRouter);
router.use(requestsRouter);
router.use(delegationsRouter);
router.use(tasksRouter);
router.use(insightsRouter);
router.use(restrictionsRouter);
router.use(supervisorRequestsRouter);
router.use(notificationsRouter);
router.use(responsibilitiesRouter);
router.use(asaRouter);
router.use(folgasRouter);
router.use(operationalCycleRouter);
router.use(activitiesRouter);
router.use(scheduleConflictsRouter);
router.use(formationsRouter);
router.use(occurrencesRouter);
router.use(entitiesRouter);
router.use(areasLocationsRouter);

export default router;
