import { Router, type IRouter } from "express";
import { eq, and, inArray, desc, sql, not } from "drizzle-orm";
import { db } from "@workspace/db";
import {
  noticesTable,
  noticeRecipientsTable,
  noticeEscalationsTable,
  usersTable,
  userRolesTable,
} from "@workspace/db";
import { requireAuth } from "../middlewares/auth.js";
import { requestLogger } from "../lib/logger.js";
import { LOG_DOMAIN } from "@workspace/shared";

const router: IRouter = Router();

// ─── Helper: extract delta ─────────────────────────────────────────────────────

function extractDelta(deltaJson: unknown): { changeBefore: string | null; changeAfter: string | null } {
  if (!deltaJson || typeof deltaJson !== "object") return { changeBefore: null, changeAfter: null };
  const d = deltaJson as Record<string, unknown>;
  return {
    changeBefore: typeof d.before === "string" ? d.before : null,
    changeAfter:  typeof d.after  === "string" ? d.after  : null,
  };
}

// ─── Helper: build full notice detail ─────────────────────────────────────────

async function buildNoticeDetail(noticeId: string) {
  const [notice] = await db
    .select({
      id: noticesTable.id,
      title: noticesTable.title,
      content: noticesTable.content,
      urgency: noticesTable.urgency,
      type: noticesTable.type,
      status: noticesTable.status,
      requiresConfirmation: noticesTable.requiresConfirmation,
      autoGenerated: noticesTable.autoGenerated,
      sourceType: noticesTable.sourceType,
      sourceId: noticesTable.sourceId,
      deltaJson: noticesTable.deltaJson,
      publishedAt: noticesTable.publishedAt,
      expiresAt: noticesTable.expiresAt,
      cancelledAt: noticesTable.cancelledAt,
      createdAt: noticesTable.createdAt,
      authorId: noticesTable.authorId,
      authorName: usersTable.name,
    })
    .from(noticesTable)
    .leftJoin(usersTable, eq(noticesTable.authorId, usersTable.id))
    .where(eq(noticesTable.id, noticeId));

  if (!notice) return null;

  const recipients = await db
    .select({
      id: noticeRecipientsTable.id,
      userId: noticeRecipientsTable.userId,
      groupId: noticeRecipientsTable.groupId,
      status: noticeRecipientsTable.status,
      sentAt: noticeRecipientsTable.sentAt,
      viewedAt: noticeRecipientsTable.viewedAt,
      confirmedAt: noticeRecipientsTable.confirmedAt,
    })
    .from(noticeRecipientsTable)
    .where(eq(noticeRecipientsTable.noticeId, noticeId));

  const userIds = [...new Set(recipients.map((r) => r.userId))];
  const users =
    userIds.length > 0
      ? await db
          .select({ id: usersTable.id, name: usersTable.name })
          .from(usersTable)
          .where(inArray(usersTable.id, userIds))
      : [];
  const userNameMap = new Map(users.map((u) => [u.id, u.name]));
  const { changeBefore, changeAfter } = extractDelta(notice.deltaJson);

  return {
    ...notice,
    changeBefore,
    changeAfter,
    deltaJson: undefined,
    recipients: recipients.map((r) => ({
      ...r,
      userName: userNameMap.get(r.userId) ?? null,
    })),
  };
}

// ─── GET /notices ──────────────────────────────────────────────────────────────

router.get("/notices", requireAuth, async (req, res): Promise<void> => {
  const log = requestLogger(LOG_DOMAIN.AVISOS, req.requestId, req.correlationId);
  const userId = req.user!.sub;
  const operationId = req.query.operationId as string | undefined;
  const status      = req.query.status      as string | undefined;

  try {
    const userRoles = await db
      .select({ operationId: userRolesTable.operationId, role: userRolesTable.role })
      .from(userRolesTable)
      .where(and(eq(userRolesTable.userId, userId), eq(userRolesTable.active, true)));

    const adminOpIds = userRoles
      .filter((r) => ["ADMIN", "SUPERVISOR_A", "SUPERVISOR_B"].includes(r.role))
      .map((r) => r.operationId);

    if (adminOpIds.length === 0) { res.json([]); return; }

    const targetOpIds =
      operationId && adminOpIds.includes(operationId) ? [operationId] : adminOpIds;

    const baseCondition = inArray(noticesTable.operationId, targetOpIds);
    const whereClause   = status
      ? and(baseCondition, eq(noticesTable.status, status as any))
      : baseCondition;

    const notices = await db
      .select({
        id: noticesTable.id,
        title: noticesTable.title,
        content: noticesTable.content,
        urgency: noticesTable.urgency,
        type: noticesTable.type,
        status: noticesTable.status,
        requiresConfirmation: noticesTable.requiresConfirmation,
        autoGenerated: noticesTable.autoGenerated,
        publishedAt: noticesTable.publishedAt,
        expiresAt: noticesTable.expiresAt,
        createdAt: noticesTable.createdAt,
        authorId: noticesTable.authorId,
        authorName: usersTable.name,
      })
      .from(noticesTable)
      .leftJoin(usersTable, eq(noticesTable.authorId, usersTable.id))
      .where(whereClause)
      .orderBy(desc(noticesTable.createdAt));

    const noticeIds = notices.map((n) => n.id);
    const recipientCounts =
      noticeIds.length > 0
        ? await db
            .select({
              noticeId: noticeRecipientsTable.noticeId,
              total:    sql<number>`cast(count(*) as int)`,
              confirmed: sql<number>`cast(sum(case when ${noticeRecipientsTable.status} = 'CONFIRMED' then 1 else 0 end) as int)`,
            })
            .from(noticeRecipientsTable)
            .where(inArray(noticeRecipientsTable.noticeId, noticeIds))
            .groupBy(noticeRecipientsTable.noticeId)
        : [];

    const countMap = new Map(recipientCounts.map((r) => [r.noticeId, r]));

    res.json(
      notices.map((n) => ({
        ...n,
        recipientCount: countMap.get(n.id)?.total    ?? 0,
        confirmedCount: countMap.get(n.id)?.confirmed ?? 0,
      }))
    );
  } catch (err) {
    log.error({ err }, "erro ao listar avisos");
    res.status(500).json({ error: "Erro interno" });
  }
});

// ─── POST /notices ────────────────────────────────────────────────────────────

router.post("/notices", requireAuth, async (req, res): Promise<void> => {
  const log = requestLogger(LOG_DOMAIN.AVISOS, req.requestId, req.correlationId);
  const userId = req.user!.sub;
  const {
    operationId,
    title,
    content,
    urgency = "INFORMATIVE",
    type = "INFORMATIVE",
    requiresConfirmation = false,
    expiresAt,
    recipientUserIds = [],
    changeBefore,
    changeAfter,
  } = req.body as {
    operationId: string;
    title?: string;
    content: string;
    urgency?: string;
    type?: string;
    requiresConfirmation?: boolean;
    expiresAt?: string;
    recipientUserIds?: string[];
    changeBefore?: string;
    changeAfter?: string;
  };

  if (!operationId || !content) {
    res.status(400).json({ error: "operationId e content são obrigatórios" });
    return;
  }

  const deltaJson = (changeBefore || changeAfter)
    ? { before: changeBefore ?? null, after: changeAfter ?? null }
    : null;

  try {
    const [notice] = await db
      .insert(noticesTable)
      .values({
        authorId: userId,
        operationId,
        title: title ?? null,
        content,
        urgency: urgency as any,
        type: type as any,
        status: "DRAFT",
        requiresConfirmation,
        deltaJson,
        expiresAt: expiresAt ? new Date(expiresAt) : null,
      })
      .returning();

    let targetUserIds: string[] = [...recipientUserIds];
    if (targetUserIds.length === 0) {
      const members = await db
        .select({ userId: userRolesTable.userId })
        .from(userRolesTable)
        .where(and(eq(userRolesTable.operationId, operationId), eq(userRolesTable.active, true)));
      targetUserIds = [...new Set(members.map((m) => m.userId))];
    }

    if (targetUserIds.length > 0) {
      await db.insert(noticeRecipientsTable).values(
        targetUserIds.map((uid) => ({
          noticeId: notice.id,
          userId: uid,
          groupId: null as string | null,
          status: "PENDING" as const,
        }))
      );
    }

    const detail = await buildNoticeDetail(notice.id);
    res.status(201).json(detail);
  } catch (err) {
    log.error({ err }, "erro ao criar aviso");
    res.status(500).json({ error: "Erro interno" });
  }
});

// ─── GET /notices/:noticeId ───────────────────────────────────────────────────

router.get("/notices/:noticeId", requireAuth, async (req, res): Promise<void> => {
  const log = requestLogger(LOG_DOMAIN.AVISOS, req.requestId, req.correlationId);
  const noticeId = String(req.params.noticeId);
  try {
    const detail = await buildNoticeDetail(noticeId);
    if (!detail) { res.status(404).json({ error: "Aviso não encontrado" }); return; }
    res.json(detail);
  } catch (err) {
    log.error({ err }, "erro ao obter aviso");
    res.status(500).json({ error: "Erro interno" });
  }
});

// ─── PATCH /notices/:noticeId ─────────────────────────────────────────────────

router.patch("/notices/:noticeId", requireAuth, async (req, res): Promise<void> => {
  const log = requestLogger(LOG_DOMAIN.AVISOS, req.requestId, req.correlationId);
  const noticeId = String(req.params.noticeId);
  const { title, content, urgency, type, requiresConfirmation, expiresAt, changeBefore, changeAfter } = req.body;

  try {
    const [existing] = await db
      .select({ status: noticesTable.status })
      .from(noticesTable)
      .where(eq(noticesTable.id, noticeId));

    if (!existing) { res.status(404).json({ error: "Aviso não encontrado" }); return; }
    if (existing.status !== "DRAFT") {
      res.status(400).json({ error: "Apenas avisos em rascunho podem ser editados" });
      return;
    }

    const updates: Record<string, unknown> = {};
    if (title              !== undefined) updates.title              = title;
    if (content            !== undefined) updates.content            = content;
    if (urgency            !== undefined) updates.urgency            = urgency;
    if (type               !== undefined) updates.type               = type;
    if (requiresConfirmation !== undefined) updates.requiresConfirmation = requiresConfirmation;
    if (expiresAt          !== undefined) updates.expiresAt          = expiresAt ? new Date(expiresAt) : null;
    if (changeBefore !== undefined || changeAfter !== undefined) {
      updates.deltaJson = (changeBefore || changeAfter)
        ? { before: changeBefore ?? null, after: changeAfter ?? null }
        : null;
    }

    await db
      .update(noticesTable)
      .set(updates as any)
      .where(eq(noticesTable.id, noticeId));

    const detail = await buildNoticeDetail(noticeId);
    res.json(detail);
  } catch (err) {
    log.error({ err }, "erro ao atualizar aviso");
    res.status(500).json({ error: "Erro interno" });
  }
});

// ─── POST /notices/:noticeId/publish ──────────────────────────────────────────

router.post("/notices/:noticeId/publish", requireAuth, async (req, res): Promise<void> => {
  const log = requestLogger(LOG_DOMAIN.AVISOS, req.requestId, req.correlationId);
  const noticeId = String(req.params.noticeId);

  try {
    const [existing] = await db
      .select({ status: noticesTable.status })
      .from(noticesTable)
      .where(eq(noticesTable.id, noticeId));

    if (!existing) { res.status(404).json({ error: "Aviso não encontrado" }); return; }
    if (existing.status !== "DRAFT") {
      res.status(400).json({ error: "Apenas rascunhos podem ser publicados" });
      return;
    }

    const now = new Date();
    await db
      .update(noticesTable)
      .set({ status: "PUBLISHED", publishedAt: now })
      .where(eq(noticesTable.id, noticeId));

    await db
      .update(noticeRecipientsTable)
      .set({ status: "SENT", sentAt: now })
      .where(
        and(
          eq(noticeRecipientsTable.noticeId, noticeId),
          eq(noticeRecipientsTable.status, "PENDING")
        )
      );

    const detail = await buildNoticeDetail(noticeId);
    res.json(detail);
  } catch (err) {
    log.error({ err }, "erro ao publicar aviso");
    res.status(500).json({ error: "Erro interno" });
  }
});

// ─── POST /notices/:noticeId/cancel ───────────────────────────────────────────

router.post("/notices/:noticeId/cancel", requireAuth, async (req, res): Promise<void> => {
  const log = requestLogger(LOG_DOMAIN.AVISOS, req.requestId, req.correlationId);
  const noticeId = String(req.params.noticeId);

  try {
    const [existing] = await db
      .select({ status: noticesTable.status })
      .from(noticesTable)
      .where(eq(noticesTable.id, noticeId));

    if (!existing) { res.status(404).json({ error: "Aviso não encontrado" }); return; }

    await db
      .update(noticesTable)
      .set({ status: "CANCELLED", cancelledAt: new Date() })
      .where(eq(noticesTable.id, noticeId));

    const detail = await buildNoticeDetail(noticeId);
    res.json(detail);
  } catch (err) {
    log.error({ err }, "erro ao cancelar aviso");
    res.status(500).json({ error: "Erro interno" });
  }
});

// ─── POST /notices/:noticeId/escalate ─────────────────────────────────────────

router.post("/notices/:noticeId/escalate", requireAuth, async (req, res): Promise<void> => {
  const log = requestLogger(LOG_DOMAIN.AVISOS, req.requestId, req.correlationId);
  const noticeId = String(req.params.noticeId);
  const escalatedBy = req.user!.sub;
  const { reason } = req.body as { reason?: string };

  try {
    const [existing] = await db
      .select({ status: noticesTable.status, requiresConfirmation: noticesTable.requiresConfirmation })
      .from(noticesTable)
      .where(eq(noticesTable.id, noticeId));

    if (!existing) { res.status(404).json({ error: "Aviso não encontrado" }); return; }
    if (existing.status !== "PUBLISHED") {
      res.status(400).json({ error: "Apenas avisos publicados podem ser escalados" });
      return;
    }

    const now = new Date();

    // Mark notice type as ESCALATED
    await db
      .update(noticesTable)
      .set({ type: "ESCALATED" })
      .where(eq(noticesTable.id, noticeId));

    // Find unconfirmed recipients
    const unconfirmedRecipients = await db
      .select({ id: noticeRecipientsTable.id, userId: noticeRecipientsTable.userId })
      .from(noticeRecipientsTable)
      .where(
        and(
          eq(noticeRecipientsTable.noticeId, noticeId),
          not(eq(noticeRecipientsTable.status, "CONFIRMED"))
        )
      );

    if (unconfirmedRecipients.length > 0) {
      // Update recipient statuses to ESCALATED
      await db
        .update(noticeRecipientsTable)
        .set({ status: "ESCALATED", escalatedAt: now })
        .where(
          and(
            eq(noticeRecipientsTable.noticeId, noticeId),
            not(eq(noticeRecipientsTable.status, "CONFIRMED"))
          )
        );

      // Insert escalation records for each unconfirmed recipient
      await db.insert(noticeEscalationsTable).values(
        unconfirmedRecipients.map((r) => ({
          noticeId,
          recipientId: r.userId,
          escalatedBy,
          reason: reason ?? null,
        }))
      );
    }

    log.info({ noticeId, escalatedBy, count: unconfirmedRecipients.length }, "aviso escalado");
    res.status(204).send();
  } catch (err) {
    log.error({ err }, "erro ao escalar aviso");
    res.status(500).json({ error: "Erro interno" });
  }
});

// ─── GET /my-notices ──────────────────────────────────────────────────────────

router.get("/my-notices", requireAuth, async (req, res): Promise<void> => {
  const log = requestLogger(LOG_DOMAIN.AVISOS, req.requestId, req.correlationId);
  const userId = req.user!.sub;

  try {
    const rows = await db
      .select({
        id: noticesTable.id,
        title: noticesTable.title,
        content: noticesTable.content,
        urgency: noticesTable.urgency,
        type: noticesTable.type,
        status: noticesTable.status,
        requiresConfirmation: noticesTable.requiresConfirmation,
        deltaJson: noticesTable.deltaJson,
        publishedAt: noticesTable.publishedAt,
        expiresAt: noticesTable.expiresAt,
        createdAt: noticesTable.createdAt,
        authorName: usersTable.name,
        recipientId: noticeRecipientsTable.id,
        recipientStatus: noticeRecipientsTable.status,
        viewedAt: noticeRecipientsTable.viewedAt,
        confirmedAt: noticeRecipientsTable.confirmedAt,
      })
      .from(noticeRecipientsTable)
      .innerJoin(noticesTable, eq(noticeRecipientsTable.noticeId, noticesTable.id))
      .leftJoin(usersTable, eq(noticesTable.authorId, usersTable.id))
      .where(
        and(
          eq(noticeRecipientsTable.userId, userId),
          eq(noticesTable.status, "PUBLISHED")
        )
      )
      .orderBy(desc(noticesTable.publishedAt));

    res.json(rows.map((r) => {
      const { deltaJson, ...rest } = r;
      const { changeBefore, changeAfter } = extractDelta(deltaJson);
      return { ...rest, changeBefore, changeAfter };
    }));
  } catch (err) {
    log.error({ err }, "erro ao listar meus avisos");
    res.status(500).json({ error: "Erro interno" });
  }
});

// ─── POST /notices/:noticeId/view ─────────────────────────────────────────────

router.post("/notices/:noticeId/view", requireAuth, async (req, res): Promise<void> => {
  const log = requestLogger(LOG_DOMAIN.AVISOS, req.requestId, req.correlationId);
  const noticeId = String(req.params.noticeId);
  const userId = req.user!.sub;

  try {
    await db
      .update(noticeRecipientsTable)
      .set({ status: "VIEWED", viewedAt: new Date() })
      .where(
        and(
          eq(noticeRecipientsTable.noticeId, noticeId),
          eq(noticeRecipientsTable.userId, userId),
          inArray(noticeRecipientsTable.status, ["SENT", "PENDING"] as any[])
        )
      );
    res.status(204).send();
  } catch (err) {
    log.error({ err }, "erro ao marcar visualizado");
    res.status(500).json({ error: "Erro interno" });
  }
});

// ─── POST /notices/:noticeId/confirm ──────────────────────────────────────────

router.post("/notices/:noticeId/confirm", requireAuth, async (req, res): Promise<void> => {
  const log = requestLogger(LOG_DOMAIN.AVISOS, req.requestId, req.correlationId);
  const noticeId = String(req.params.noticeId);
  const userId = req.user!.sub;

  try {
    await db
      .update(noticeRecipientsTable)
      .set({ status: "CONFIRMED", confirmedAt: new Date() })
      .where(
        and(
          eq(noticeRecipientsTable.noticeId, noticeId),
          eq(noticeRecipientsTable.userId, userId)
        )
      );
    res.status(204).send();
  } catch (err) {
    log.error({ err }, "erro ao confirmar aviso");
    res.status(500).json({ error: "Erro interno" });
  }
});

export default router;
