// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/meu-dia/Atencao.tsx": () => import("../components/mockups/meu-dia/Atencao.tsx"),
  "./components/mockups/meu-dia/Critico.tsx": () => import("../components/mockups/meu-dia/Critico.tsx"),
  "./components/mockups/meu-dia/Normal.tsx": () => import("../components/mockups/meu-dia/Normal.tsx"),
  "./components/mockups/meu-dia/PosConfirmacao.tsx": () => import("../components/mockups/meu-dia/PosConfirmacao.tsx"),
  "./components/mockups/meu-dia/Vazio.tsx": () => import("../components/mockups/meu-dia/Vazio.tsx")
};
