// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/meu-dia/Atencao.tsx": () => import("../components/mockups/meu-dia/Atencao.tsx"),
  "./components/mockups/meu-dia/Critico.tsx": () => import("../components/mockups/meu-dia/Critico.tsx"),
  "./components/mockups/meu-dia/Normal.tsx": () => import("../components/mockups/meu-dia/Normal.tsx"),
  "./components/mockups/meu-dia/PosConfirmacao.tsx": () => import("../components/mockups/meu-dia/PosConfirmacao.tsx"),
  "./components/mockups/meu-dia/Vazio.tsx": () => import("../components/mockups/meu-dia/Vazio.tsx"),
  "./components/mockups/painel-operacional/Atencao.tsx": () => import("../components/mockups/painel-operacional/Atencao.tsx"),
  "./components/mockups/painel-operacional/Critico.tsx": () => import("../components/mockups/painel-operacional/Critico.tsx"),
  "./components/mockups/painel-operacional/MultiplasExcecoes.tsx": () => import("../components/mockups/painel-operacional/MultiplasExcecoes.tsx"),
  "./components/mockups/painel-operacional/PosResolucao.tsx": () => import("../components/mockups/painel-operacional/PosResolucao.tsx"),
  "./components/mockups/painel-operacional/Pronta.tsx": () => import("../components/mockups/painel-operacional/Pronta.tsx"),
  "./components/mockups/painel-operacional/SemExcecoes.tsx": () => import("../components/mockups/painel-operacional/SemExcecoes.tsx")
};
