import { type FormEvent, type ReactNode, useEffect, useMemo, useState } from "react";
import { Grid2X2, KeyRound, List, MapPin, Pencil, Plus, Search, Trash2, UserRound, Users, X } from "lucide-react";
import { ApiError, customFetch } from "@workspace/api-client-react";
import exampleData from "../../../../design_handoff_my_asa/dados-de-exemplo.json";
import "./cadastros.css";

export type CadastroScreen = "people" | "areas" | "locations";
type ShellRole = "adm" | "dir" | "sup" | "mem";
type Location = { id: string; name: string; type?: string; closed?: boolean };
type Area = { id: string; name: string; active?: boolean };
type Person = { id: string; name?: string; displayName?: string; fullName?: string; nomeCompleto?: string; email?: string | null; areaId?: string | null; areaName?: string | null; status?: string; personStatus?: string; profile?: string; isAdmin?: boolean; supervisorOperationIds?: string[] };
type SupervisorMap = { id?: string; areaId: string; locationId: string; supervisorId?: string; supervisorName: string; active?: boolean };
type EditTarget = { type: CadastroScreen; item?: Person | Area | Location } | null;

const sampleLocations: Location[] = exampleData.locais.map((item) => ({ id: item.id, name: item.nome, type: item.operacao, closed: false }));
const sampleAreas: Area[] = exampleData.areas.map((item) => ({ id: item.id, name: item.nome, active: true }));
const samplePeople: Person[] = exampleData.pessoas.map((item, index) => ({
  id: `sample-person-${index}`, name: item.nome_de_exibicao, displayName: item.nome_de_exibicao, fullName: item.nome_completo,
  areaId: item.area, areaName: sampleAreas.find((area) => area.id === item.area)?.name ?? null,
  profile: item.perfil, status: "ACTIVE", personStatus: "ACTIVE",
}));
const sampleSupervisors: SupervisorMap[] = exampleData.supervisao_por_area_local
  .filter((item): item is typeof item & { local: string } => Boolean(item.local))
  .map((item, index) => ({ id: `sample-supervisor-${index}`, areaId: item.area, locationId: item.local, supervisorName: item.supervisor, active: true }));
const screenCopy: Record<CadastroScreen, { singular: string; plural: string; empty: string; action: string }> = {
  people: { singular: "pessoa", plural: "Pessoas", empty: "Nenhuma pessoa para este recorte.", action: "Nova pessoa" },
  areas: { singular: "área", plural: "Áreas", empty: "Nenhuma área para este recorte.", action: "Nova área" },
  locations: { singular: "local", plural: "Locais", empty: "Nenhum local para este recorte.", action: "Novo local" },
};
const personName = (person: Person) => person.displayName ?? person.name ?? "Pessoa";
const formalName = (person: Person) => person.fullName ?? person.nomeCompleto ?? personName(person);
const initials = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
const profileLabel = (person: Person) => person.profile === "DIR" ? "Direção" : person.profile === "ADM" || person.isAdmin ? "Administração" : person.profile === "SUP" || (person.supervisorOperationIds?.length ?? 0) > 0 ? "Supervisão" : "Elenco";
const stateLabel = (person: Person) => person.status === "INACTIVE" || person.personStatus === "ARCHIVED" || person.personStatus === "LEFT" ? "desligada" : person.personStatus === "ON_LEAVE" ? "afastada" : "ativa";
const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("pt-BR");

function Dialog({ children, onClose }: { children: ReactNode; onClose: () => void }) {
  return <div className="cad-dialog-backdrop" role="presentation" onMouseDown={onClose}><section className="cad-dialog" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><button className="cad-dialog-close" aria-label="Fechar" onClick={onClose}><X size={20}/></button>{children}</section></div>;
}

export default function CadastrosPage({ screen, role }: { screen: CadastroScreen; role: ShellRole }) {
  const review = import.meta.env.DEV && (new URLSearchParams(window.location.search).get("amostra") === "1" || window.sessionStorage.getItem("myasa-review-sample") === "1");
  const [people, setPeople] = useState<Person[]>([]), [areas, setAreas] = useState<Area[]>([]), [locations, setLocations] = useState<Location[]>([]), [supervisors, setSupervisors] = useState<SupervisorMap[]>([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState(""), [query, setQuery] = useState(""), [areaFilter, setAreaFilter] = useState("");
  const [edit, setEdit] = useState<EditTarget>(null), [removing, setRemoving] = useState<EditTarget>(null), [saving, setSaving] = useState(false), [peopleView, setPeopleView] = useState<"grid" | "list">("grid");
  const [resetting, setResetting] = useState<Person | null>(null), [provisoria, setProvisoria] = useState(""), [resetError, setResetError] = useState("");
  const canEdit = role === "adm", copy = screenCopy[screen];
  const load = async () => {
    setLoading(true); setError("");
    if (review) { setPeople(samplePeople); setAreas(sampleAreas); setLocations(sampleLocations); setSupervisors(sampleSupervisors); setLoading(false); return; }
    try {
      const [peopleResult, areaResult, locationResult] = await Promise.all([customFetch<{ users?: Person[] }>("/api/users"), customFetch<{ areas?: Area[] }>("/api/areas").catch(() => ({ areas: [] })), customFetch<{ locations?: Location[] }>("/api/locations").catch(() => ({ locations: [] }))]);
      const nextAreas = areaResult.areas ?? [], nextLocations = locationResult.locations ?? [];
      const mappings = await Promise.all(nextAreas.map(async (area) => { try { return (await customFetch<{ supervisors?: SupervisorMap[] }>(`/api/areas/${area.id}/local-supervisors`)).supervisors ?? []; } catch { return []; } }));
      setAreas(nextAreas); setLocations(nextLocations); setPeople((peopleResult.users ?? []).map((person) => ({ ...person, areaName: person.areaName ?? nextAreas.find((area) => area.id === person.areaId)?.name ?? null }))); setSupervisors(mappings.flat());
    } catch { setError(`Não consegui carregar ${copy.plural.toLocaleLowerCase("pt-BR")} agora.`); } finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, [review]);
  // Na amostra a sessão é visual. Aplicamos o mesmo recorte que o servidor
  // aplicará na sessão real, para que Deborah nunca revise Bailarinos por
  // acidente e o estado da prévia seja representativo.
  const reviewAreaScope = review && (role === "sup" || role === "mem") ? "patinadores" : "";
  const scopedPeople = useMemo(() => { const queryText = normalize(query); return people.filter((person) => (!reviewAreaScope || person.areaId === reviewAreaScope) && (!areaFilter || person.areaId === areaFilter) && (!queryText || normalize(`${personName(person)} ${formalName(person)}`).includes(queryText))); }, [people, areaFilter, query, reviewAreaScope]);
  const filteredAreas = useMemo(() => areas.filter((area) => (!reviewAreaScope || area.id === reviewAreaScope) && (!query || normalize(area.name).includes(normalize(query)))), [areas, query, reviewAreaScope]);
  const filteredLocations = useMemo(() => locations.filter((location) => !query || normalize(location.name).includes(normalize(query))), [locations, query]);
  const supervisorFor = (areaId?: string | null) => supervisors.filter((item) => item.areaId === areaId && item.active !== false).map((item) => `${locations.find((location) => location.id === item.locationId)?.name ?? "Local"} · ${item.supervisorName}`).join(" · ");
  const save = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!edit || review) { setEdit(null); return; } const form = new FormData(event.currentTarget); setSaving(true); setError("");
    try {
      if (edit.type === "locations") { const item = edit.item as Location | undefined, body = { name: String(form.get("name") ?? "").trim(), type: String(form.get("type") ?? "parque").trim() }; if (item) await customFetch(`/api/locations/${item.id}`, { method: "PATCH", body: JSON.stringify(body) }); else await customFetch("/api/locations", { method: "POST", body: JSON.stringify(body) }); }
      if (edit.type === "areas") { const item = edit.item as Area | undefined, body = { name: String(form.get("name") ?? "").trim() }; if (item) await customFetch(`/api/areas/${item.id}`, { method: "PATCH", body: JSON.stringify(body) }); else await customFetch("/api/areas", { method: "POST", body: JSON.stringify(body) }); }
      if (edit.type === "people") { const item = edit.item as Person | undefined, body = { fullName: String(form.get("fullName") ?? "").trim(), email: String(form.get("email") ?? "").trim() || undefined, ...(!item ? { password: String(form.get("password") ?? "") } : {}) }, areaId = String(form.get("areaId") ?? ""); const result = item ? await customFetch<{ user: Person }>(`/api/users/${item.id}`, { method: "PATCH", body: JSON.stringify(body) }) : await customFetch<{ user: Person }>("/api/users", { method: "POST", body: JSON.stringify(body) }); if (areaId) await customFetch(`/api/users/${result.user.id}/operational-scope`, { method: "PUT", body: JSON.stringify({ areaId }) }); }
      setEdit(null); await load();
    } catch { setError(`Não consegui salvar esta ${copy.singular}. Confira os campos e tente de novo.`); } finally { setSaving(false); }
  };
  const remove = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!removing || review) { setRemoving(null); return; } const item = removing.item as Person | Area | Location, reason = String(new FormData(event.currentTarget).get("reason") ?? "").trim(); setSaving(true);
    try { const path = removing.type === "people" ? `/api/users/${item.id}` : removing.type === "areas" ? `/api/areas/${item.id}` : `/api/locations/${item.id}`; await customFetch(path, { method: "DELETE", body: JSON.stringify(removing.type === "people" ? { reason } : {}) }); setRemoving(null); await load(); } catch { setError(`Não consegui encerrar esta ${screenCopy[removing.type].singular}.`); } finally { setSaving(false); }
  };
  const resetPassword = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!resetting || review) { setResetting(null); return; } const reason = String(new FormData(event.currentTarget).get("reason") ?? "").trim(); setSaving(true); setResetError("");
    try { const result = await customFetch<{ senhaProvisoria: string }>(`/api/users/${resetting.id}/password-reset`, { method: "POST", body: JSON.stringify({ reason }) }); setProvisoria(result.senhaProvisoria); }
    catch (err) { setResetError(err instanceof ApiError && (err.data as { message?: string } | null)?.message ? (err.data as { message: string }).message : "Não consegui redefinir a senha agora. Tente de novo."); } finally { setSaving(false); }
  };
  const closeReset = () => { if (saving) return; setResetting(null); setProvisoria(""); setResetError(""); };
  const searchControl = <div className="cad-search"><Search size={17}/><input aria-label={`Buscar ${copy.singular}`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Buscar ${copy.singular}`}/></div>;
  const peopleContent = peopleView === "grid" ? <div className="cad-grid cad-people-grid">{scopedPeople.map((person) => <article className="cad-card cad-person" key={person.id}><header><span className="cad-avatar">{initials(personName(person))}</span><div><h2>{personName(person)}</h2><p>{person.areaName ?? "Sem área"}</p></div><span className={`cad-state ${stateLabel(person)}`}>{stateLabel(person)}</span></header><div className="cad-person-info"><span>{profileLabel(person)}</span>{supervisorFor(person.areaId) && <span>supervisão por local: {supervisorFor(person.areaId)}</span>}</div>{canEdit && <footer><button onClick={() => setEdit({ type: "people", item: person })}><Pencil size={15}/>Editar</button><button className="cad-danger-link" onClick={() => setRemoving({ type: "people", item: person })}><Trash2 size={15}/>Desligar</button></footer>}</article>)}</div> : <div className="cad-person-list" role="list">{scopedPeople.map((person) => <article className="cad-person-row" key={person.id} role="listitem"><span className="cad-avatar">{initials(personName(person))}</span><div className="cad-row-name"><strong>{personName(person)}</strong><span>{profileLabel(person)}</span></div><div className="cad-row-context"><strong>{person.areaName ?? "Sem área"}</strong><span>Local definido na Programação</span></div><div className="cad-row-supervisor"><span>Supervisão por local</span><strong>{supervisorFor(person.areaId) || "Não definida"}</strong></div><span className={`cad-state ${stateLabel(person)}`}>{stateLabel(person)}</span>{canEdit && <div className="cad-row-actions"><button onClick={() => setEdit({ type: "people", item: person })}><Pencil size={15}/><span>Editar</span></button><button className="cad-danger-link" onClick={() => setRemoving({ type: "people", item: person })}><Trash2 size={15}/><span>Desligar</span></button></div>}</article>)}</div>;
  return <section className="cad-page"><div className="cad-toolbar"><p>{role === "dir" ? "Somente leitura" : role === "sup" ? "Seu escopo" : role === "mem" ? "Sua área" : "Cadastro da operação"}</p>{canEdit && <button className="cad-primary" onClick={() => setEdit({ type: screen })}><Plus size={17}/>{copy.action}</button>}</div><div className="cad-filters">{searchControl}{screen === "people" && <><select aria-label="Filtrar por área" value={areaFilter} onChange={(event) => setAreaFilter(event.target.value)}><option value="">Todas as áreas</option>{areas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select><div className="cad-view-toggle" aria-label="Visualização"><button type="button" className={peopleView === "grid" ? "active" : ""} aria-pressed={peopleView === "grid"} title="Ver em grade" onClick={() => setPeopleView("grid")}><Grid2X2 size={17}/><span>Grade</span></button><button type="button" className={peopleView === "list" ? "active" : ""} aria-pressed={peopleView === "list"} title="Ver em lista" onClick={() => setPeopleView("list")}><List size={18}/><span>Lista</span></button></div></>}</div>
    {error && <div className="cad-error" role="alert">{error}<button onClick={() => void load()}>Tentar de novo</button></div>}
    {loading ? <div className="cad-skeletons" aria-busy="true"><i/><i/><i/></div> : screen === "people" ? peopleContent : screen === "areas" ? <div className="cad-grid">{filteredAreas.map((area) => { const members = people.filter((person) => person.areaId === area.id && stateLabel(person) === "ativa"), leads = supervisors.filter((item) => item.areaId === area.id && item.active !== false); return <article className="cad-card cad-area" key={area.id}><header><span className="cad-icon"><Users size={19}/></span><div><h2>{area.name}</h2><p>{members.length} {members.length === 1 ? "pessoa ativa" : "pessoas ativas"}</p></div><span className="cad-state ativa">ativa</span></header><div className="cad-area-supervisors">{leads.length ? leads.map((lead) => <span key={lead.id ?? `${lead.locationId}-${lead.supervisorName}`}>{locations.find((location) => location.id === lead.locationId)?.name ?? "Local"} · <b>{lead.supervisorName}</b></span>) : <span>Sem supervisão local cadastrada</span>}</div>{canEdit && <footer><button onClick={() => setEdit({ type: "areas", item: area })}><Pencil size={15}/>Editar</button><button className="cad-danger-link" onClick={() => setRemoving({ type: "areas", item: area })}><Trash2 size={15}/>Desativar</button></footer>}</article>; })}</div> : <div className="cad-grid">{filteredLocations.map((location) => <article className="cad-card cad-location" key={location.id}><header><span className="cad-icon"><MapPin size={19}/></span><div><h2>{location.name}</h2><p>{location.type ?? "Operação"}</p></div><span className={`cad-state ${location.closed ? "encerrada" : "ativa"}`}>{location.closed ? "encerrado" : "ativo"}</span></header><div className="cad-location-info"><span>Programação define quem atua no dia</span><span>{areas.map((area) => area.name).join(" · ") || "Sem áreas cadastradas"}</span></div>{canEdit && <footer><button onClick={() => setEdit({ type: "locations", item: location })}><Pencil size={15}/>Editar</button><button className="cad-danger-link" onClick={() => setRemoving({ type: "locations", item: location })}><Trash2 size={15}/>Encerrar</button></footer>}</article>)}</div>}
    {!loading && ((screen === "people" && !scopedPeople.length) || (screen === "areas" && !filteredAreas.length) || (screen === "locations" && !filteredLocations.length)) && <div className="cad-empty"><UserRound size={26}/><strong>{copy.empty}</strong><span>{canEdit ? "Você pode começar pelo botão acima." : "Quando houver algo no seu acesso, aparece aqui."}</span></div>}
    {edit && <Dialog onClose={() => !saving && setEdit(null)}><h2>{edit.item ? `Editar ${screenCopy[edit.type].singular}` : screenCopy[edit.type].action}</h2><p>{edit.type === "people" ? "Nome completo é o cadastro formal. O nome de exibição continua sendo escolhido pela própria pessoa no Perfil. O local é definido na Programação e na Escala, nunca neste cadastro." : "Este cadastro será usado pelas telas operacionais."}</p><form className="cad-form" onSubmit={save}>{edit.type === "people" ? <><label>Nome completo<input name="fullName" required defaultValue={edit.item ? formalName(edit.item as Person) : ""}/></label><label>E-mail<input type="email" name="email" defaultValue={(edit.item as Person | undefined)?.email ?? ""}/></label>{!edit.item && <label>Senha inicial<input type="password" name="password" minLength={8} required autoComplete="new-password"/><small>A pessoa deverá trocar a senha no primeiro acesso.</small></label>}<label>Área<select name="areaId" required defaultValue={(edit.item as Person | undefined)?.areaId ?? ""}><option value="" disabled>Escolha a área</option>{areas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select></label></> : <><label>Nome<input name="name" required defaultValue={(edit.item as Area | Location | undefined)?.name ?? ""}/></label>{edit.type === "locations" && <label>Tipo de local<input name="type" defaultValue={(edit.item as Location | undefined)?.type ?? "parque"}/></label>}</>}<footer><button type="button" onClick={() => setEdit(null)}>Cancelar</button><button className="cad-primary" disabled={saving}>{saving ? "Salvando…" : edit.item ? "Salvar" : "Criar"}</button></footer></form>{edit.type === "people" && edit.item && <div className="cad-reset-row"><span>Esqueceu a senha?</span><button type="button" onClick={() => { setResetting(edit.item as Person); setEdit(null); }}><KeyRound size={15}/>Redefinir senha</button></div>}</Dialog>}
    {resetting && <Dialog onClose={closeReset}><h2>Redefinir senha de {personName(resetting)}</h2>{provisoria ? <><p>Passe esta senha provisória só para {personName(resetting)}. No próximo login o app pede para trocar por uma senha dela. Ela some desta tela quando você fechar.</p><output className="cad-temp-password" aria-label="Senha provisória">{provisoria}</output><p className="cad-reset-note">As sessões abertas de {personName(resetting)} foram encerradas. Ficou no Registro, com o motivo.</p><footer className="cad-form-footer"><button className="cad-primary" type="button" onClick={closeReset}>Pronto, já passei</button></footer></> : <><p>O app gera uma senha provisória e encerra as sessões abertas da pessoa. Ela troca a senha no próximo login.</p><form className="cad-form" onSubmit={resetPassword}><label>Motivo<textarea name="reason" required placeholder="Ex.: esqueceu a senha e pediu no camarim"/></label>{resetError && <p className="cad-error" role="alert">{resetError}</p>}<footer><button type="button" onClick={closeReset}>Cancelar</button><button className="cad-primary" disabled={saving}>{saving ? "Gerando…" : "Gerar senha provisória"}</button></footer></form></>}</Dialog>}
    {removing && <Dialog onClose={() => !saving && setRemoving(null)}><h2>{removing.type === "people" ? "Desligar pessoa" : removing.type === "locations" ? "Encerrar local" : "Desativar área"}</h2><p>{removing.type === "people" ? "A pessoa não será apagada: o histórico permanece preservado." : "O cadastro deixa de aparecer nas listas ativas, sem apagar o histórico."}</p><form className="cad-form" onSubmit={remove}>{removing.type === "people" && <label>Motivo<textarea name="reason" required placeholder="Escreva o motivo do desligamento"/></label>}<footer><button type="button" onClick={() => setRemoving(null)}>Cancelar</button><button className="cad-danger" disabled={saving}>{saving ? "Salvando…" : "Confirmar"}</button></footer></form></Dialog>}
  </section>;
}
