import { pgTable, text, uuid, timestamp, boolean, jsonb, pgEnum } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { usersTable } from "./identity.js";
import { operationsTable, operationalGroupsTable } from "./organization.js";

// ─── Enums ─────────────────────────────────────────────────────────────────────

export const noticeUrgencyEnum = pgEnum("notice_urgency", ["INFORMATIVE", "IMPORTANT", "CRITICAL"]);

export const noticeTypeEnum = pgEnum("notice_type", [
  "INFORMATIVE",
  "IMPORTANT",
  "PERSISTENT",
  "ESCALATED",
]);

export const noticeStatusEnum = pgEnum("notice_status", [
  "DRAFT",
  "PUBLISHED",
  "EXPIRED",
  "CANCELLED",
]);

export const noticeRecipientStatusEnum = pgEnum("notice_recipient_status", [
  "PENDING",
  "SENT",
  "VIEWED",
  "CONFIRMED",
  "ESCALATED",
]);

export const messageContextTypeEnum = pgEnum("message_context_type", [
  "REQUEST", "DELIVERY", "NOTICE", "MO", "DAILY_BOOK", "FREE",
]);

// ─── Notices ───────────────────────────────────────────────────────────────────

export const noticesTable = pgTable("notices", {
  id: uuid("id").primaryKey().defaultRandom(),
  authorId: uuid("author_id").notNull().references(() => usersTable.id),
  operationId: uuid("operation_id").notNull().references(() => operationsTable.id),
  urgency: noticeUrgencyEnum("urgency").notNull().default("INFORMATIVE"),
  type: noticeTypeEnum("type").notNull().default("INFORMATIVE"),
  status: noticeStatusEnum("status").notNull().default("DRAFT"),
  title: text("title"),
  content: text("content").notNull(),
  requiresConfirmation: boolean("requires_confirmation").notNull().default(false),
  deltaJson: jsonb("delta_json"),
  autoGenerated: boolean("auto_generated").notNull().default(false),
  sourceType: text("source_type"),
  sourceId: text("source_id"),
  publishedAt: timestamp("published_at", { withTimezone: true }),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
});

// ─── Notice Recipients ─────────────────────────────────────────────────────────

export const noticeRecipientsTable = pgTable("notice_recipients", {
  id: uuid("id").primaryKey().defaultRandom(),
  noticeId: uuid("notice_id").notNull().references(() => noticesTable.id),
  userId: uuid("user_id").notNull().references(() => usersTable.id),
  groupId: uuid("group_id").references(() => operationalGroupsTable.id),
  status: noticeRecipientStatusEnum("status").notNull().default("PENDING"),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  viewedAt: timestamp("viewed_at", { withTimezone: true }),
  confirmedAt: timestamp("confirmed_at", { withTimezone: true }),
  escalatedAt: timestamp("escalated_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ─── Notice Escalations ────────────────────────────────────────────────────────

export const noticeEscalationsTable = pgTable("notice_escalations", {
  id: uuid("id").primaryKey().defaultRandom(),
  noticeId: uuid("notice_id").notNull().references(() => noticesTable.id),
  recipientId: uuid("recipient_id").notNull().references(() => usersTable.id),
  escalatedBy: uuid("escalated_by").references(() => usersTable.id),
  reason: text("reason"),
  escalatedAt: timestamp("escalated_at", { withTimezone: true }).notNull().defaultNow(),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ─── Notice Confirmations (legacy — kept for compat) ──────────────────────────

export const noticeConfirmationsTable = pgTable("notice_confirmations", {
  id: uuid("id").primaryKey().defaultRandom(),
  noticeId: uuid("notice_id").notNull().references(() => noticesTable.id),
  userId: uuid("user_id").notNull().references(() => usersTable.id),
  confirmedAt: timestamp("confirmed_at", { withTimezone: true }).notNull().defaultNow(),
});

// ─── Messages ─────────────────────────────────────────────────────────────────

export const messagesTable = pgTable("messages", {
  id: uuid("id").primaryKey().defaultRandom(),
  senderId: uuid("sender_id").notNull().references(() => usersTable.id),
  recipientId: uuid("recipient_id").references(() => usersTable.id),
  groupId: uuid("group_id").references(() => operationalGroupsTable.id),
  contextType: messageContextTypeEnum("context_type"),
  contextId: uuid("context_id"),
  content: text("content").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ─── Zod schemas ───────────────────────────────────────────────────────────────

export const insertNoticeSchema = createInsertSchema(noticesTable).omit({ id: true, createdAt: true });
export type InsertNotice = z.infer<typeof insertNoticeSchema>;
export type Notice = typeof noticesTable.$inferSelect;

export const insertNoticeRecipientSchema = createInsertSchema(noticeRecipientsTable).omit({ id: true, createdAt: true });
export type InsertNoticeRecipient = z.infer<typeof insertNoticeRecipientSchema>;
export type NoticeRecipient = typeof noticeRecipientsTable.$inferSelect;

export const insertNoticeEscalationSchema = createInsertSchema(noticeEscalationsTable).omit({ id: true, createdAt: true });
export type InsertNoticeEscalation = z.infer<typeof insertNoticeEscalationSchema>;
export type NoticeEscalation = typeof noticeEscalationsTable.$inferSelect;

export const insertNoticeConfirmationSchema = createInsertSchema(noticeConfirmationsTable).omit({ id: true });
export type InsertNoticeConfirmation = z.infer<typeof insertNoticeConfirmationSchema>;
export type NoticeConfirmation = typeof noticeConfirmationsTable.$inferSelect;

export const insertMessageSchema = createInsertSchema(messagesTable).omit({ id: true, createdAt: true });
export type InsertMessage = z.infer<typeof insertMessageSchema>;
export type Message = typeof messagesTable.$inferSelect;
